# Configuration file to run tests on Travis-CI via GitHub notifications
# See http://travis-ci.org/

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - "pip install ."

script:
  - "python setup.py test"
