# Configuration file to run tests on Travis-CI via GitHub notifications
# See http://travis-ci.org/

language: python
python:
  - "2.7"

install:
  - "pip install ."

script:
  - "python setup.py test"
